spring:
  application:
    name: sbf-app
  cloud:
    refresh:
      enabled: false
    config:
      uri: http://localhost:8888
  zipkin:
    baseUrl : http://localhost:9411
    enabled : true
  locator:
    discovery:
      enabled : true

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

